<?xml version="1.0" encoding="utf-8"?>
<gui-model>
	<controls>
		<control>
			<sides>
				<left>10</left>
				<bottom>10</bottom>
				<right>498.714386</right>
				<top>237.160019</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Screen</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>141.575623</left>
				<bottom>201.643158</bottom>
				<right>367.351898</right>
				<top>63.5905838</top>
			</sides>
			<borderSize>2</borderSize>
			<name>dialog</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>170.224991</left>
				<bottom>109.872986</bottom>
				<right>209.374924</right>
				<top>87.1930237</top>
			</sides>
			<borderSize>2</borderSize>
			<name>OK</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>297.971863</left>
				<bottom>109.87722</bottom>
				<right>336.581879</right>
				<top>87.1929474</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Cancel</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>170.225006</left>
				<bottom>179.562744</bottom>
				<right>336.581909</right>
				<top>160.122742</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Exit without saving?</name>
			<nameHeight>10</nameHeight>
		</control>
	</controls>
	<constraints>
		<constraint>
			<text>dhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>0</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>1.65751028</first-local-side>
			<second-local-side>8.65750885</second-local-side>
		</constraint>
		<constraint>
			<text>dhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>0</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>1.65749073</first-local-side>
			<second-local-side>8.65749359</second-local-side>
		</constraint>
		<constraint>
			<text>1.618bh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>80.0020599</first-local-side>
			<second-local-side>87.0020447</second-local-side>
		</constraint>
		<constraint>
			<text>bh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>209.632477</first-local-side>
			<second-local-side>216.632477</second-local-side>
		</constraint>
		<constraint>
			<text>bw</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>56.0929451</first-local-side>
			<second-local-side>63.0929337</second-local-side>
		</constraint>
		<constraint>
			<text>bw</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>56.0972252</first-local-side>
			<second-local-side>63.0972404</second-local-side>
		</constraint>
		<constraint>
			<text>bhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>56.1562195</first-local-side>
			<second-local-side>63.1562195</second-local-side>
		</constraint>
		<constraint>
			<text>bhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>56.0297203</first-local-side>
			<second-local-side>63.0297203</second-local-side>
		</constraint>
		<constraint>
			<text>3bhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>55.9622231</first-local-side>
			<second-local-side>62.9622383</second-local-side>
		</constraint>
		<constraint>
			<text>dvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>0</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>498.963135</first-local-side>
			<second-local-side>505.963135</second-local-side>
		</constraint>
		<constraint>
			<text>dvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>0</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>499.224365</first-local-side>
			<second-local-side>506.224426</second-local-side>
		</constraint>
		<constraint>
			<text>10mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>4</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>367.653748</first-local-side>
			<second-local-side>374.653717</second-local-side>
		</constraint>
		<constraint>
			<text>50mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>374.84375</first-local-side>
			<second-local-side>381.843781</second-local-side>
		</constraint>
		<constraint>
			<text>dh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>499.161255</first-local-side>
			<second-local-side>506.161255</second-local-side>
		</constraint>
		<constraint>
			<text>1.618dh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>1.630023</first-local-side>
			<second-local-side>8.63003922</second-local-side>
		</constraint>
		<constraint>
			<text>0px</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>130.622482</first-local-side>
			<second-local-side>137.622482</second-local-side>
		</constraint>
		<constraint>
			<text>0px</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>130.757507</first-local-side>
			<second-local-side>137.757507</second-local-side>
		</constraint>
		<constraint>
			<text>bvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>4</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>367.586243</first-local-side>
			<second-local-side>374.586243</second-local-side>
		</constraint>
		<constraint>
			<text>bvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>367.518738</first-local-side>
			<second-local-side>374.518738</second-local-side>
		</constraint>
		<constraint>
			<text>15mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>367.518738</first-local-side>
			<second-local-side>374.518738</second-local-side>
		</constraint>
		<constraint>
			<text>bvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>367.455627</first-local-side>
			<second-local-side>374.455627</second-local-side>
		</constraint>
		<constraint>
			<text>0px</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>248.843109</first-local-side>
			<second-local-side>255.843109</second-local-side>
		</constraint>
		<constraint>
			<text>0px</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>249.374344</first-local-side>
			<second-local-side>256.374329</second-local-side>
		</constraint>
	</constraints>
</gui-model>
