<?xml version="1.0" encoding="utf-8"?>
<gui-model>
	<controls>
		<control>
			<sides>
				<left>10</left>
				<bottom>10</bottom>
				<right>320.480011</right>
				<top>237.160019</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Screen</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>81.8099899</left>
				<bottom>198.720001</bottom>
				<right>245.430023</right>
				<top>72.3600159</top>
			</sides>
			<borderSize>2</borderSize>
			<name>dialog</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>95.8499908</left>
				<bottom>108.81002</bottom>
				<right>134.999924</right>
				<top>86.1300583</top>
			</sides>
			<borderSize>2</borderSize>
			<name>OK</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>193.049988</left>
				<bottom>109.079994</bottom>
				<right>231.660004</right>
				<top>86.129982</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Cancel</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>95.8500061</left>
				<bottom>180.35997</bottom>
				<right>231.660034</right>
				<top>160.919968</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Exit without saving?</name>
			<nameHeight>10</nameHeight>
		</control>
	</controls>
	<constraints>
		<constraint>
			<text>dhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>0</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>1.65751028</first-local-side>
			<second-local-side>8.65750885</second-local-side>
		</constraint>
		<constraint>
			<text>dhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>0</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>1.65749073</first-local-side>
			<second-local-side>8.65749359</second-local-side>
		</constraint>
		<constraint>
			<text>1.618bh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>109.76503</first-local-side>
			<second-local-side>116.765015</second-local-side>
		</constraint>
		<constraint>
			<text>bh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>135.684998</first-local-side>
			<second-local-side>142.684998</second-local-side>
		</constraint>
		<constraint>
			<text>bh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>183.069977</first-local-side>
			<second-local-side>190.069977</second-local-side>
		</constraint>
		<constraint>
			<text>bw</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>76.554985</first-local-side>
			<second-local-side>83.5549698</second-local-side>
		</constraint>
		<constraint>
			<text>bw</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>76.8250046</first-local-side>
			<second-local-side>83.8250122</second-local-side>
		</constraint>
		<constraint>
			<text>bhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>76.3525162</first-local-side>
			<second-local-side>83.3525085</second-local-side>
		</constraint>
		<constraint>
			<text>bhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>76.7574997</first-local-side>
			<second-local-side>83.7575073</second-local-side>
		</constraint>
		<constraint>
			<text>3bhm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>76.6900024</first-local-side>
			<second-local-side>83.6900177</second-local-side>
		</constraint>
		<constraint>
			<text>dvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>0</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>322.32251</first-local-side>
			<second-local-side>329.322479</second-local-side>
		</constraint>
		<constraint>
			<text>dvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>0</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>322.05249</first-local-side>
			<second-local-side>329.052551</second-local-side>
		</constraint>
		<constraint>
			<text>10mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>4</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>247.060013</first-local-side>
			<second-local-side>254.059967</second-local-side>
		</constraint>
		<constraint>
			<text>50mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>256.375</first-local-side>
			<second-local-side>263.375031</second-local-side>
		</constraint>
		<constraint>
			<text>dh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>322.255005</first-local-side>
			<second-local-side>329.255005</second-local-side>
		</constraint>
		<constraint>
			<text>1.618dh</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>1.630023</first-local-side>
			<second-local-side>8.63003922</second-local-side>
		</constraint>
		<constraint>
			<text>0px</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>130.622482</first-local-side>
			<second-local-side>137.622482</second-local-side>
		</constraint>
		<constraint>
			<text>0px</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>130.757507</first-local-side>
			<second-local-side>137.757507</second-local-side>
		</constraint>
		<constraint>
			<text>bvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>4</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>246.992508</first-local-side>
			<second-local-side>253.992508</second-local-side>
		</constraint>
		<constraint>
			<text>bvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>246.925003</first-local-side>
			<second-local-side>253.925003</second-local-side>
		</constraint>
		<constraint>
			<text>15mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>246.925003</first-local-side>
			<second-local-side>253.925003</second-local-side>
		</constraint>
		<constraint>
			<text>bvm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>247.127518</first-local-side>
			<second-local-side>254.127518</second-local-side>
		</constraint>
		<constraint>
			<text>0px</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>160.389984</first-local-side>
			<second-local-side>167.389984</second-local-side>
		</constraint>
	</constraints>
</gui-model>
