<?xml version="1.0" encoding="utf-8"?>
<!--
	Four equally-sized squares are positioned at same
	distances relative to different corners of the window.
-->
<gui-model>
	<controls>
		<control>
			<sides>
				<left>10</left>
				<bottom>10</bottom>
				<right>206.136353</right>
				<top>179.000015</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Screen</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>35.6624985</left>
				<bottom>155.417511</bottom>
				<right>80.2406311</right>
				<top>125.725006</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Alpha</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>141.028976</left>
				<bottom>156.220001</bottom>
				<right>178.3125</right>
				<top>128.132507</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Bravo</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>35.9326706</left>
				<bottom>64.1999969</bottom>
				<right>79.9704361</right>
				<top>32.1000023</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Charlie</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>136.436066</left>
				<bottom>62.3274956</bottom>
				<right>175.610794</right>
				<top>31.2975006</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Delta</name>
			<nameHeight>10</nameHeight>
		</control>
	</controls>
	<constraints>
		<constraint>
			<text>20mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>0</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>141.855637</first-local-side>
			<second-local-side>148.855652</second-local-side>
		</constraint>
		<constraint>
			<text>20mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>0</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>54.1138496</first-local-side>
			<second-local-side>61.1138344</second-local-side>
		</constraint>
		<constraint>
			<text>30mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>118.613754</first-local-side>
			<second-local-side>125.613747</second-local-side>
		</constraint>
		<constraint>
			<text>30mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>80.3879318</first-local-side>
			<second-local-side>87.3879623</second-local-side>
		</constraint>
		<constraint>
			<text>20mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>0</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>156.305817</first-local-side>
			<second-local-side>163.305817</second-local-side>
		</constraint>
		<constraint>
			<text>20mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>0</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>138.64563</first-local-side>
			<second-local-side>145.645645</second-local-side>
		</constraint>
		<constraint>
			<text>30mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>121.288757</first-local-side>
			<second-local-side>128.288757</second-local-side>
		</constraint>
		<constraint>
			<text>30mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>2</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>133.746597</first-local-side>
			<second-local-side>140.746597</second-local-side>
		</constraint>
		<constraint>
			<text>20mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>0</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>44.0175056</first-local-side>
			<second-local-side>51.0175018</second-local-side>
		</constraint>
		<constraint>
			<text>20mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>0</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>60.9356461</first-local-side>
			<second-local-side>67.9356689</second-local-side>
		</constraint>
		<constraint>
			<text>30mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>64.1774979</first-local-side>
			<second-local-side>71.1775208</second-local-side>
		</constraint>
		<constraint>
			<text>30mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>3</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>80.1177444</first-local-side>
			<second-local-side>87.1177673</second-local-side>
		</constraint>
		<constraint>
			<text>20mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>0</control>
				<side>bottom</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>148.065613</first-local-side>
			<second-local-side>155.065613</second-local-side>
		</constraint>
		<constraint>
			<text>20mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>0</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>44.2181244</first-local-side>
			<second-local-side>51.2181206</second-local-side>
		</constraint>
		<constraint>
			<text>30mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>4</control>
				<side>right</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>left</side>
			</second-end-point>
			<first-local-side>62.7062454</first-local-side>
			<second-local-side>69.7062607</second-local-side>
		</constraint>
		<constraint>
			<text>30mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>4</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>129.153687</first-local-side>
			<second-local-side>136.153702</second-local-side>
		</constraint>
	</constraints>
</gui-model>
