<?xml version="1.0" encoding="utf-8"?>
<gui-model>
	<controls>
		<control>
			<sides>
				<left>10</left>
				<bottom>10</bottom>
				<right>272.0833</right>
				<top>247.2222</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Screen</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>29.61875</left>
				<bottom>200.025</bottom>
				<right>86.38805</right>
				<top>153.1056</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Alice</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>155.851</left>
				<bottom>205.6694</bottom>
				<right>225.3141</right>
				<top>117.1222</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Bob</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>71.22604</left>
				<bottom>105.4806</bottom>
				<right>122.7063</right>
				<top>44.45</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Malory</name>
			<nameHeight>10</nameHeight>
		</control>
		<control>
			<sides>
				<left>95.20313</left>
				<bottom>233.8917</bottom>
				<right>146.3307</right>
				<top>213.4306</top>
			</sides>
			<borderSize>2</borderSize>
			<name>Hello World!</name>
			<nameHeight>10</nameHeight>
		</control>
	</controls>
	<constraints>
		<constraint>
			<text>5mm</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>164.5986</first-local-side>
			<second-local-side>171.5986</second-local-side>
		</constraint>
		<constraint>
			<text>5kg</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>1</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>90.20456</first-local-side>
			<second-local-side>97.20456</second-local-side>
		</constraint>
		<constraint>
			<text>42</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>3</control>
				<side>top</side>
			</second-end-point>
			<first-local-side>217.8473</first-local-side>
			<second-local-side>224.8473</second-local-side>
		</constraint>
		<constraint>
			<text>!!</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>4</control>
				<side>top</side>
			</first-end-point>
			<second-end-point>
				<control>1</control>
				<side>bottom</side>
			</second-end-point>
			<first-local-side>102.105</first-local-side>
			<second-local-side>109.105</second-local-side>
		</constraint>
		<constraint>
			<text>5pt</text>
			<text-height>7</text-height>
			<first-end-point>
				<control>2</control>
				<side>left</side>
			</first-end-point>
			<second-end-point>
				<control>4</control>
				<side>right</side>
			</second-end-point>
			<first-local-side>189.0285</first-local-side>
			<second-local-side>196.0285</second-local-side>
		</constraint>
	</constraints>
</gui-model>
